### ISSUE TITLE
Crash while attaching to TTY

### ISSUE THREAD

**Issue by xdavidhu** [nopernik/SSHPry2.0#2]
Hi!

SSHPry is not working for me, when I'm tying to attach to a TTY, it crashes.
I'm using Python 3.5.2 on Ubuntu 16.04.4 x64.
I thought maybe I should use pyton2, but the code looks pretty much like its written in python3.

Crash log:
```
[+] Attaching to 1668 at /dev/pts/1...
(<class 'TypeError'>, TypeError("a bytes-like object is required, not 'str'",), <traceback object at 0x7fad8a9ae848>)
root@ubnt:~/SSHPry2.0#
```

Thank you for your help.

**Comment by catchra** [comment]
Python 2.7.17
Ubuntu 18.04.4 LTS (GNU/Linux 4.14.173-173 armv7l)

```root@ODroidXU4:~/SSHPry2.0# python sshpry2.py --tty /dev/pts/0

SSHPry2 SSH-TTY control by @nopernik 2017

[+] Getting available ssh connections...
[+] Target TTY keystrokes file: 'keys-2020-03-26-1646.sshpry.log'
[+] Target TTY session file: 'sess-2020-03-26-1646.sshpry.log'

[+] Attaching to 25548 at /dev/pts/0...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "sshpry2.py", line 105, in PryonTTY
    sshpipe = Popen(['strace', '-s', '16384', '-p', z.pid, '-e', 'read,write'], shell=False, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by nopernik** [comment]
Unfortunately no Python 3 support.
`sudo apt install strace`

**Comment by NihilistPenguin** [comment]
The TypeError is fixable and then the code will run with Python3, but another issue arises. For some reason, the entire ssh session gets slowed down so it feels like you're typing with 20 seconds of input lag. No clue why.
