### ISSUE TITLE
i cant get session ssh

### ISSUE THREAD

**Issue by strongpapazola** [nopernik/SSHPry2.0#4]
root@kali:~/Desktop/SSHPry2.0# ./sshpry2.py --tty /dev/pts/2

SSHPry2 SSH-TTY control by @nopernik 2017

[+] Getting available ssh connections...
[+] Target TTY keystrokes file: 'keys-2020-03-28-0834.sshpry.log'
[+] Target TTY session file: 'sess-2020-03-28-0834.sshpry.log'

[+] Attaching to 18809 at /dev/pts/2...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./sshpry2.py", line 105, in PryonTTY
    sshpipe = Popen(['strace', '-s', '16384', '-p', z.pid, '-e', 'read,write'], shell=False, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by nopernik** [comment]
Duplicate #3
