### ISSUE TITLE
Note strace dependency somewhere

### ISSUE THREAD

**Issue by ChillerDragon** [nopernik/SSHPry2.0#5]
A ``apt install strace`` for apt based systems and other package managers in the readme would be nice. And maybe fail with a nicer message than this:

```
Exception in thread Thread-1:                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner                                                                                                                                           
    self.run()                                                                                                                                                                                                    
  File "/usr/lib/python3.7/threading.py", line 865, in run                                                                                                                                                        
    self._target(*self._args, **self._kwargs)                                                                                                                                                                     
  File "sshpry2.py", line 105, in PryonTTY                                                                                                                                                                        
    sshpipe = Popen(['strace', '-s', '16384', '-p', z.pid, '-e', 'read,write'], shell=False, stdout=PIPE, stderr=PIPE)                                                                                            
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__                                                                                                                                                  
    restore_signals, start_new_session)                                                                                                                                                                           
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child                                                                                                                                           
    raise child_exception_type(errno_num, err_msg, err_filename)                                                                                                                                                  
FileNotFoundError: [Errno 2] No such file or directory: 'strace': 'strace' 
```

**Comment by ChillerDragon** [comment]
Ok I guess since https://github.com/nopernik/SSHPry2.0/issues/3 you are aware of the issue.
